# Generated by Django 5.2.14 on 2026-05-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=264)),
                ('destination', models.CharField(max_length=264)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
